### ISSUE TITLE
Problem mit Parameter "Name"

### ISSUE THREAD

**Issue by mschwentner** [nhmvienna/AutDeNovo#3]
Hi Martin,

hab die pipeline gestartet. Hat folgenden Fehler gezeigt:

Please see below, which parameter is missing:
*******************************
Name=Yeti_01 is missing: The name of the sample needs to be specified

ich habe bei mir gesetzt:

  Name=Pleustid \
  OutputFolder=/media/inter/mschwentner/Genome_assembly_test/test1lib \
  Fwd=/media/inter/mschwentner/Illumina_trimmed/C16_1_val_1.fq.gz \
  Rev=/media/inter/mschwentner/Illumina_trimmed/C16_2_val_2.fq.gz \
  ONT=/media/inter/mschwentner/MinIon_runs/HAC/HAC_C16II_pass \
  BuscoDB=arthropoda_odb10

Dann solllte er eigentlich doch den Parameter name als Pleustid erkennen, oder? Eine Idee was ich da falsch gesetzt habe?

Beste Grüße,
Maartin

**Comment by capoony** [comment]
Lieber Martin, Du musst vor jeden Zeilenumbruch einen Backslash setzen, das könnte das Problem gewesen sein. I.e. 

```bash
Name=Pleustid \
OutputFolder=/media/inter/mschwentner/Genome_assembly_test/test1lib \
Fwd=/media/inter/mschwentner/Illumina_trimmed/C16_1_val_1.fq.gz \
Rev=/media/inter/mschwentner/Illumina_trimmed/C16_2_val_2.fq.gz \
ONT=/media/inter/mschwentner/MinIon_runs/HAC/HAC_C16II_pass \
BuscoDB=arthropoda_odb10
```

Cheers, Martin
